### ISSUE TITLE
工程运行启动崩溃

### ISSUE THREAD

**Issue by luyaotree** [EastWoodYang/Mis#1]
11-15 10:35:36.314 22440-22440/com.eastwood.demo.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eastwood.demo.app, PID: 22440
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.eastwood.demo.app/com.eastwood.demo.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'com.eastwood.demo.library.LibraryModel com.eastwood.demo.library.ILibraryService.getLibraryInfo()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2696)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2762)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5902)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:948)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:809)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'com.eastwood.demo.library.LibraryModel com.eastwood.demo.library.ILibraryService.getLibraryInfo()' on a null object reference
        at com.eastwood.demo.app.MainActivity.onCreate(MainActivity.java:26)
        at android.app.Activity.performCreate(Activity.java:6367)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2649)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2762) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:5902) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:948) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:809)

**Comment by EastWoodYang** [comment]
这只是一个demo工程。。。配合测试用的。
这两天在做迭代，会有比较大的调整。

**Comment by EastWoodYang** [comment]
已经调整过来了。近期会有比较大的改动。
