### ISSUE TITLE
kotlin语言下使用data class打包后会产生运行时异常

### ISSUE THREAD

**Issue by Simon1121** [EastWoodYang/Mis#10]
data class(val id:Long)会被编译器生成hashcode方法，但是hashcode方法的实现使用了jdk高版本的api，如Long.hashcode(id)，导致运行在android4.4系统上时抛出运行时异常

**Comment by YummyLau** [comment]
> data class(val id:Long)会被编译器生成hashcode方法，但是hashcode方法的实现使用了jdk高版本的api，如Long.hashcode(id)，导致运行在android4.4系统上时抛出运行时异常

能否提供给一下本地kotlin插件版本及java版本。也贴一下出错的字节码及android4.4机型。

**Comment by YummyLau** [comment]
从android官方上，可以将Kotlin编译的JVM目标设置为“1.6”，因为Kotlin 1.3.30已经开始从android.compileOptions中的Java版本推断出JVM目标，如果同时设置了sourceCompatibility和targetCompatibility，则选择“1.8”到那个或更高。
In the module's build.gradle, add:
tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
    kotlinOptions {
        jvmTarget = '1.6'
    }
}
尝试下。
可以参考下 https://issuetracker.google.com/issues/129730297
后续更新插件解决。感谢提交issues

**Comment by Simon1121** [comment]
jvmTarget外部设置无效，这个应该是由mis内部设定？

Caused by: java.lang.NoSuchMethodError: Ljava/lang/Long;.hashCode
 	at jzg.com.vlc_shopping_app.user.model.User.hashCode(User.kt)
 	at jzg.com.vlc_shopping_app.user.service.impl.UserConverter.convert(UserServiceImpl.kt:196)
 	at jzg.com.vlc_shopping_app.user.service.impl.UserConverter.convert(UserServiceImpl.kt:193)
 	at sm.rx2utils.map.ObjectConverterFunction.apply(ObjectConverterFunction.java:15)
 	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:57)
 	at io.reactivex.internal.operators.observable.ObservableScalarXMap$ScalarDisposable.run(ObservableScalarXMap.java:248)
 	at io.reactivex.internal.operators.observable.ObservableJust.subscribeActual(ObservableJust.java:35)
 	at io.reactivex.Observable.subscribe(Observable.java:12090)
 	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
 	at io.reactivex.Observable.subscribe(Observable.java:12090)
 	at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
 	at io.reactivex.Observable.subscribe(Observable.java:12090)
 	at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(ObservableFlatMap.java:55)
 	at io.reactivex.Observable.subscribe(Observable.java:12090)
 	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
 	... 7 more

**Comment by EastWoodYang** [comment]
```
mis {
    ...
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_6
        targetCompatibility JavaVersion.VERSION_1_6
    }
    ...
}
```
降低target看看

**Comment by Simon1121** [comment]
这个操作貌似可以，我继续观察
mis {
    ...
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_6
        targetCompatibility JavaVersion.VERSION_1_6
    }
    ...
}

**Comment by EastWoodYang** [comment]
感谢继续反馈
